### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by Inoshiro90** [Emurasoft/excel-csv-import#125]
Hello,
is it possible to support the dark mode in Excel? I have my version of Excel in dark mode and can hardly see the labels, if at all.

![Screenshot 2024-06-19 223005](https://github.com/Emurasoft/excel-csv-import/assets/110790047/fcd1fd1e-6b90-4099-bef0-e6b911865896)

**Comment by MakotoE** [comment]
Thanks for creating an issue for this. If you have time, feel free to submit a PR. If not, I'll try to take a look when possible.
