### ISSUE TITLE
export does not correctly escape double quoted text

### ISSUE THREAD

**Issue by sanderpost** [Emurasoft/excel-csv-import#46]
Reproduction:

1. Create excel file, on A1 add text: `this is some text "{{blaat}}" whatever` 
2. Export as CSV > export type: textbox.

Expected results: "this is some text ""{{blaat}}"" whatever"
Actual results: "this is some text ""{{blaat}}" whatever"

All double quotes should be escaped by a double quote.

Chrome 80.0
Office Online, build: 16.0.12725.35053

**Comment by MakotoE** [comment]
Thank you; I somehow forgot to check this case.
